# Generated by Django 6.0.7 on 2026-07-16 12:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('borrowings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='borrowing',
            name='actual_return_date_isnull',
        ),
        migrations.RemoveConstraint(
            model_name='borrowing',
            name='actual_return_date__gte_borrow_date',
        ),
        migrations.AlterField(
            model_name='borrowing',
            name='actual_return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='borrowing',
            constraint=models.CheckConstraint(condition=models.Q(('actual_return_date__isnull', True), ('actual_return_date__gte', models.F('borrow_date')), _connector='OR'), name='actual_return_date_isnull_and_gte_borrow_date'),
        ),
    ]
